#!/bin/bash

# Use ffmpeg to make a clip with subtitles burned in for easy sharing.
#
# Example: https://twitter.com/deliberatecoder/status/1353123432783876097

set -ex

PRESET="veryslow"
if [ "$1" = "--quick" ]; then
  PRESET="ultrafast"
fi

set -u

RAW_DIR="/mnt/htfp/raw"

if [ "$PRESET" = "veryslow" ]; then
  FINAL_DIR="/mnt/htfp/final"
else
  FINAL_DIR="/mnt/htfp/scratch"
fi

TITLES="$(mktemp --suffix=.srt)"
echo "1
00:00:00,000 --> 00:0:03,000
How I Manage Hacker News Comments" > "$TITLES"
TITLE_FONT="Anton"
TITLE_FONT_SIZE="23"

# You can generate the subtitles using YouTube's video editor
# and downloading as SRT.
SUBTITLES="$(mktemp --suffix=.srt)"
echo "1
00:00:00,939 --> 00:00:04,000
When I manage comments,
the way I think about it is

2
00:00:04,000 --> 00:00:08,780
I try to imagine that I've just given
a tech talk at a software conference

3
00:00:08,780 --> 00:00:13,849
and so I'm now taking questions at a Q&A

4
00:00:13,849 --> 00:00:19,980
What that means is I'm going to be gracious
and professional in all the responses I give

5
00:00:19,980 --> 00:00:25,140
because if I'm on stage in front of hundreds
of people, I'm not going to be rude or snarky

6
00:00:25,140 --> 00:00:26,170
in my responses

7
00:00:26,170 --> 00:00:29,630
And so that means you definitely don't try
to dunk on people.

8
00:00:29,630 --> 00:00:34,690
If you were on stage in front of a hundred
people at a conference, even if somebody made

9
00:00:34,690 --> 00:00:38,180
a rude comment to you about your presentation,
you wouldn't say to them,

10
00:00:38,180 --> 00:00:40,629
\"Oh yeah? well you're
a stupid idiot!\"

11
00:00:40,629 --> 00:00:42,829
Because you would just look bad.

12
00:00:42,829 --> 00:00:45,359
And similarly with getting defensive.

13
00:00:45,359 --> 00:00:50,149
It's better to just behave professionally
and try to engage in a civil discussion.

14
00:00:50,149 --> 00:00:54,239
So, the things I always try to do are: appreciate
that they read my article.

15
00:00:54,239 --> 00:00:58,420
Even if they disagreed, and even if they're
being more hostile than I think they need

16
00:00:58,420 --> 00:01:03,940
to be, I want to start by appreciating that
they did take the time to read my article.

17
00:01:03,940 --> 00:01:07,270
And I want to try to consider what they're
saying to me.

18
00:01:07,270 --> 00:01:14,020
Even if it's in a hostile tone or it's overly
aggressive, I try consider what they're saying

19
00:01:14,020 --> 00:01:16,220
and if I have anything to learn from it.

20
00:01:16,220 --> 00:01:20,640
And lastly, I'll try to bend over backwards
to assume good intent.
" > "$SUBTITLES"
SUBTITLE_FONT="DejaVuSans"
SUBTITLE_FONT_SIZE="13"

INPUT_VIDEO="${FINAL_DIR}/excerpts/managing-comments.mp4"
OUTPUT_VIDEO="${FINAL_DIR}/excerpts/managing-comments-subtitled.mp4"

DURATION=81

PROGRESS_BAR_POSITION_Y=595
PROGRESS_BAR_THICKNESS=7

ffmpeg -y -i ${INPUT_VIDEO} -filter_complex "
  color=c=black:size=720x720 [black];
  [0:v] scale=w=720:h=in_h*720/in_w [scaled];
  [black][scaled] overlay=y='(main_h - overlay_h)/2' [base];

  [base] subtitles=filename=${TITLES}
      :force_style='Outline=0,Shadow=0,Fontname=${TITLE_FONT},Fontsize=${TITLE_FONT_SIZE},PrimaryColour=&Hffffff&,Alignment=6,MarginL=0' [titled];

  [titled] subtitles=filename=${SUBTITLES}
      :force_style='Fontname=${SUBTITLE_FONT},Fontsize=${SUBTITLE_FONT_SIZE},PrimaryColour=&Hffffff&Alignment=2,MarginV=13' [subtitled];

  color=c=red@0.8:size=720x${PROGRESS_BAR_THICKNESS} [bar];
  [subtitled][bar] overlay=y=${PROGRESS_BAR_POSITION_Y}:x='(t/${DURATION})*main_w-main_w'
" -t "$DURATION" -preset "$PRESET" "$OUTPUT_VIDEO"
